### ISSUE TITLE
Failed to run on ARM64

### ISSUE THREAD

**Issue by qiufengke** [MaxRev-Dev/gdal.netcore#107] opened 2023-06-12 02:43 UTC
**Describe the bug**
arm64 下 调用 GdalBase.ConfigureAll() 报错
![image](https://github.com/MaxRev-Dev/gdal.netcore/assets/14359212/5b2201c4-b806-41c2-be4d-a0fc47cf5709)

**Environment information:**
![image](https://github.com/MaxRev-Dev/gdal.netcore/assets/14359212/c10899d9-6d5f-4236-bc8f-35d96687f13b)

**Comment by MaxRev-Dev** [comment] 2023-06-12 03:19
1. Please describe your issue in English. Add issue title, possibly affected package versions, how you run them,  etc. Otherwise, this issue will be closed without hesitation.
2. From your screenshots, I can say that your distro depends on GLIBC 2.28. The latest version is supported on systems with GLIBC 2.32. [See FAQ](https://github.com/MaxRev-Dev/gdal.netcore#q-packages-does-not-work-on-centos-7-ubuntu-1804)
3. Try [this release](https://github.com/MaxRev-Dev/gdal.netcore/releases/tag/v3.3.3.110) which depends on GLIBC 2.17. Let me know if this works for you.

**Comment by qiufengke** [comment] 2023-06-12 03:56
I tried Release 3.3.3.110, but it still threw an exception.

![image](https://github.com/MaxRev-Dev/gdal.netcore/assets/14359212/e88510d0-6d3a-4939-8bee-96c4cde19955)

**Comment by MaxRev-Dev** [comment] 2023-06-12 09:24
@qiufengke I didn't notice that you're running on **arm64** platform. It's not supported. Closing this as a duplicate of #106

**Closed by MaxRev-Dev** 2023-06-12 09:24 UTC
Labels: not-a-bug, requires:more-information
