### ISSUE TITLE
[BUG] Library fails on configuring when executed directly as DLL 

### ISSUE THREAD

**Issue by Cherubix** [MaxRev-Dev/gdal.netcore#40] opened 2021-03-15 12:24 UTC
**Describe the bug**
`GdalConfigureAll` fails when used in an AddIn of another Application in Windows OS.
I developed an AddIn to [Microstation Connect Edition](https://communities.bentley.com/products/microstation/w/microstation__wiki/27351/faq---microstation) which is a CAD system.
This AddIn is a dynamic link library (DLL) with some tools for automatic drawing generation. 
`ConfigureAll` fails here:
`var executingDir = new FileInfo(Assembly.GetEntryAssembly().Location).Directory;`

**To Reproduce**
Call library DLL directly from another application or DLL without .NET executable applications. 

**Expected behavior**
Calling Assembly should not be used to define path to library contents.

**Proposed solution**
Allow the possibility to define `executingDir` from the Calling Assembly other than Entry Assembly.

**Environment information:**
 - OS (version): Windows 10
 - Package version (core): 3.2.0.300
 - Package version (runtime): 3.2.0.300 

First time for me to submit an issue. Hopefully it is correctly described. Thanks

**Comment by MaxRev-Dev** [comment] 2021-03-15 13:52
Yes, thanks for the feedback. This should be fixed by replacing `GetEntryAssembly` to `GetCurrentAssembly` method call. I will perform some refactoring to that part, so then the patch to be released. This should be done in a few days.

**Closed** 2021-03-25 10:53 UTC
Labels: bug

**Comment by Cherubix** [comment] 2021-03-29 08:05
Hi MaxRev, I believe this bug is not closed yet when your Library is used in an AddIn tool of a parent Application.
Quite often, the directory where the AddIn is placed does not correspond to the directory of parent application. In my case the main application directory is the following:
C:\Program Files\Bentley\MicroStation CONNECT Edition\MicroStation
while the addin is placed in the following folder:
C:\appl\Routing\Connect
The possibility to use separate directories for AddIn is oftne present in order to keep separate the original assemblies of parent application from the addin assemblies.

Here below a piece of source code where the Library fails on configuring:
`public static bool Initialize()
        {
            //Inizialize ApplicationInfo
            ApplicationInfo.Initialize(1);

            //Configure GDAL
            MaxRev.Gdal.Core.GdalBase.ConfigureAll();
            System.Diagnostics.Trace.WriteLine($"MaxRev Gdal configured: {MaxRev.Gdal.Core.GdalBase.IsConfigured}");
            if (!MaxRev.Gdal.Core.GdalBase.IsConfigured) {
                IsInitialized = false;
            }

            IsInitialized = true;
            return true;
        }`
The failure message is the following:
System.UnauthorizedAccessException: 'Access to path 'C:\Program Files\Bentley\MicroStation CONNECT Edition\MicroStation\gdalplugins' denied.'

A rough solution I found for another assembly developed by me, to be used both as an assembly of a parent application and as assembly of an AddIn of a parent application is as follows:
`            System.Reflection.Assembly asm;
            if (EntryOrCalling == 0)
                asm = System.Reflection.Assembly.GetEntryAssembly();
            else
                asm = System.Reflection.Assembly.GetCallingAssembly();
` 
where EntryOr Calling is a value parameter defined by the developer. So, when the assembly is used directly by the parent application EntryOrCalling is equal to 0, while when used indirectly, as an assembly of an AddIn, EntryOrCalling has a non zero value.

**Comment by MaxRev-Dev** [comment] 2021-03-30 08:00
Can you provide an installer of this application and provide some steps on setting all up?
I can not reproduce this without executable. Current version handles a lot of environments, but this is not a trivial issue. Executed in ordinary way there is always some sort of boostrapper like a calling dll and `dotnet run`. 
To make sure which part of configurator is failing, because I'm using both `Assembly.GetEntryAssembly` and `Assembly.GetCallingAssembly` 

https://github.com/MaxRev-Dev/gdal.netcore/blob/98b939d89d73790c538993ab32b718428b60c878/compile/GdalConfigureAll.cs#L46-L48
